name: Build Java Project

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stop-gracefully-jar
          path: build/libs/*.jar
